services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    expose:
      - 9200
    env_file: .env
    volumes:
      - data:/usr/share/elasticsearch/data
    restart: unless-stopped
    networks:
      - chat-network
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.15.3
    ports:
      - '5601:5601'
    env_file: .env
    restart: unless-stopped
    networks:
      - chat-network
  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:8.15.3
    expose:
      - 5044
      - 5000
      - 9600
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    restart: unless-stopped
    networks:
      - chat-network
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.15.3
    container_name: filebeat
    user: root
    command: filebeat -e -c /usr/share/filebeat/filebeat.yml
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /var/lib/docker/containers:/var/lib/docker/containers:ro
    - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    depends_on:
      - logstash
    networks:
      - chat-network

volumes:
  data:

networks:
  chat-network:
    driver: bridge
    external: true
